### ISSUE TITLE
Bodyslide importing not working?

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#102]
Hey Piranha, I'm testing that new bodyslide export/import button, and I can't get it to work properly... 
Export button seems fine, it generates a .json with all bodyslides, descriptors, etc. However, import button does nothing at all. Tried deleting all bodyslides before importing, with/without backup, and still nothing gets imported...

**Comment by Piranha91** [comment]
Weird, it works for me:

Before import:
![image](https://user-images.githubusercontent.com/63175798/219837957-ffe2ceee-3670-4243-b14e-04fb6e382b3c.png)

After import:
![image](https://user-images.githubusercontent.com/63175798/219838012-c9e00a0d-d542-472b-9fcf-6b150ed1170f.png)

Just to confirm this is the behavior you're trying to replicate?

**Comment by leonardovcr** [comment]
Yeah, that. However, I went a little bit ahead, and managed to get a somewhat succesful import after trying different ways of importing. I've noticed the following:
 - Nothing gets imported if I click on 'delete - all' bodyslides prior to importing.
 - If I click on 'delete - all', restart synthebd (to recreate the bodyslides list), and then run import again, import happens.

However, the import is done in a rather peculiar way. If the SynthEBD installation has none of the descriptors used in the imported file, than no custom descriptors are imported, only general bodyslide information (like allowed weight, probability). For example, if a SynthEBD installation has descriptors Build:Slim, Chest:Big, and the imported file has Build:Slim, Chest:Big, Chest:Small, than only Build:Slim and Chest:Big are imported. I think that kind of defeats the purpose of importing, since then one would need to configure SynthEBD with all the imported descriptors prior to importing the .json 🤔

**Comment by leonardovcr** [comment]
Oh, and another thing I've noticed... any Asset Pack annotated with custom bodyslide descriptors loses said annotations if those descriptors are not already present in the SynthEBD installation...

**Comment by leonardovcr** [comment]
Sorry, forgot another one 😆 

Custom attribute groups are also not exported to the .json file. I have one body descriptor which references two attribute groups. Those references to the attribute groups are exported, but the attribute groups themselves are not.

**Comment by Piranha91** [comment]
0.9.6.1 should fix the missing custom descriptor and attribute group import. 

One thing to note is that the importer will only import descriptors, attribute groups, etc for BodySlides that the user has existing in the settings (otherwise it would import a bunch of BodySlides that it wouldn't be able to assign, and shouldn't, because the user wouldn't actually have the corresponding xml files). SynthEBD only checks which BodySlides exist when the program first loads, so if you delete a BodySlide setting and then try to import it, it will be skipped because the importer thinks it doesn't exist. However, if you clear the annotations to let the importer know "hey, I have this bodyslide but I haven't yet annotated it", it should import the new annotations, descriptors, and attribute groups for that BodySlide.

**Comment by leonardovcr** [comment]
Thanks Piranha, latest version is now importing custom descriptors and custom attibute groups 👍 However, custom attribute groups exporting is still not working, and I think race groupings exporting is not working either, but it was working on 0.9.6 🤔

**Comment by leonardovcr** [comment]
Testing here a little bit more, I've found another issue related to importing bodyslides which are dupes of the same bodyslide... looks like only the last 'cloned' bodyslide entry is being imported.

For example, if I have three Bodyslide entries (foo, foo2, foo3) with different descriptors (because foo.xml body shape varies wildly depending on weight slider), but each Bodyslide entry references the same foo.xml bodyslide file, then only one of them gets imported. From what I could test, the last one (foo3) gets imported while the others are ignored.

**Comment by Piranha91** [comment]
Thanks for taking a look. Not much time to troubleshoot further until Tuesday due to IRL deadlines but I’ll get to it.

**Comment by leonardovcr** [comment]
Dont sweat it, take care! 🙏

**Comment by Piranha91** [comment]
Ok, I was able to duplicate and fix the issue with importing multiple bodyslides - the previous code addressed the case of having 1 imported annotation and > 1 existing annotation, but not the reverse case of 1 existing annotation and multiple imported clones. This should now be fixed in 0.9.6.2.

However, I was not able to replicate the issue of custom attribute groups not exporting. They also import correctly for me - I wonder if there's something in your hand-edited json file that's causing them to load unchecked. I took some screen recordings of how it looks for me. Is there something I'm doing that you're not, or vice versa?

Exporting:
https://i.imgur.com/8bORZlr.gif

Importing:
https://i.imgur.com/xXUcCp3.gif

I did notice in the gif above that race groupings weren't being imported so I fixed that in 0.9.6.2 as well.

**Comment by leonardovcr** [comment]
Hey Piranha, thanks for the videos, now I can see why it works for you but not for me. Indeed I'm doing things differently... If I set Race Groupings or Custom Attribute Groups on the bodyslide entry as you did, it exports fine, however, my attr groups and race groupings are set on the distribution rules of the "body descriptors":

![image](https://user-images.githubusercontent.com/13605450/220674766-e11eae7e-fbc9-45d9-8ede-ae4454552691.png)
![image](https://user-images.githubusercontent.com/13605450/220674924-e6d082ae-4bbc-4390-bb76-4f657bb6e477.png)

Oh, and the importing of cloned bodyslides are fixed now, thanks 💯

**Comment by Piranha91** [comment]
D'oh. Order of operations issue. Descriptors were getting imported before attribute groups, so the new groups didn't exist yet from the perspective of the new descriptors. Should be fixed in 0.9.6.3.

**Comment by leonardovcr** [comment]
Great, from what I could test, everything's fine now. Also noticed that new overwrite/merge option, really nice touch 👍 Thanks!

**Comment by leonardovcr** [comment]
Sorry, looks like I prematurely closed the issue... testing a bit more and can attest that Attr. groups are still not being exported :(

Here's how I'm setting them up:

![image](https://user-images.githubusercontent.com/13605450/220985365-db429a9a-fa09-4093-9a06-1d65919ca24a.png)
![image](https://user-images.githubusercontent.com/13605450/220985552-cc424cc9-09f2-4f78-b541-a24275f95065.png)

If I manually add the attr. groups to the .json file, they are succesfully imported.

**Comment by Piranha91** [comment]
Argh, things are always more complex than I think they are :). The exporter only exports attribute/race groups that are referenced by the BodySlide configuration to avoid cluttering the exported file with unused/test groups. I was having it check the individual bodyslides to see which groups were referenced, but not the descriptor rules. Should be fixed in 0.9.6.4, though I confess I made it on the bus on the way to work and only had a brief time to test.

**Comment by leonardovcr** [comment]
Yeah, that's I.T..... nothing is as simple as it seems 😆 
Well, the bus coding worked, race groupings and attr. groups set on body descriptors are now all being correctly exported 👍 Confidently closing the issue now, thanks!
