### ISSUE TITLE
Allowed BodySlides are disallowed

### ISSUE THREAD

**Issue by HitBug83** [Synthesis-Collective/SynthEBD#30]
Hello Piranha91, there is an issue with the Allowed Bodyslides setting. I'm using Autobody.

The descriptors I put in the "Allowed Bodyslide Descriptors" box are in fact disallowed, as stated by the verbose log.

The "Disallowed Bodyslide Descriptors" seem to be ruled out as they should. There is a minor issue where there is no mention of it in the verbose log. But it seems it still works because I ran a few times the patcher and the disallowed descriptor was never picked up.

Last thing : if I set "Allowed Bodyslide Descriptors" in a parent subgroup, its childs ignore the set up and they can pick any BodySlide.

**Comment by Piranha91** [comment]
I believe both issues should be fixed in 0.7.7.1 (just released). That said, still haven't had much time for testing as I'm away on a trip. If you get a chance please let me know how your experience with it is.

**Comment by HitBug83** [comment]
0.7.7.1 did not fix this issue.

Allowed descriptors are still read as disallowed. The child subgroups now inherit the allowed descriptors setting from their parents, but it is still recognized as disallowed.

As for the disallowed setting, I tried this time with more than 2 presets and it's not working at all, sorry for misleading you in my first post. Still no input in the verbose log so I thought at first all Bodyslides were allowed, but sometimes the NPC doen't get any BodySlide, so hard to tell what's going on.

**Comment by Piranha91** [comment]
Ah, bummer. I'm back from my travels so I'll be able to debug properly now,
but won't have a chance until tomorrow at earliest. Thanks for letting me
know.

**Comment by Piranha91** [comment]
I believe I have tracked down both issues contributing to this behavior and fixed them in v0.7.7.2. Please let me know if you now see the expected asset:bodyslide agreement.

**Comment by HitBug83** [comment]
So far so good !

I did some testing and everything looked coherent regarding BodySlides distribution.

There is still a minor issue : when consistency is disabled, the patcher still tries to match the BodySlide selection with the consistency BodySlide, so I have to delete the esp if I want to reset all combinations and have faster patching runs.

---------

I also have a suggestion : you could add a (rather advanced) setting allowing the user to choose which subgroups can be used as a seed. With my heavy config files mixing a bunch of different skin mods, I have some really heavy logs when some very specific assets are chosen as seeds. For example, in the Tempered Skins mods, there is a different specular map for each diffuse map. In the end, the corresponding diffuse will inevitably be selected by the patcher after it tries every single other option.

I think most users build their setups around diffuse and normal maps (and put them higher in the tree) and they want in most cases the distribution of corresponding specular/subsurface dictated by which diffuse/normal is selected as a seed, and not the other way around.

If I understand correctly how the patching process works, with the trimming of subgroups from the top of the tree to the bottom, I think it would speed up the patching with heavy configs, allow a better control over the distribution pattern, and spare the user from setting redundant attribute allowances on the linked subgroups at the bottom of the tree.

**Comment by Piranha91** [comment]
Ah I'll take a look at the consistency issue -will keep this issue open for now until I fix it. Thanks again for pointing it out.

Regarding the seed recommendation, I could do it but it would be a fair bit of work, and I'm not sure it would achieve the desired result. For example, in Tempered Skins for Females, you are right that there's a different specular body map for each diffuse body map. If the patcher is "obligated" to start with Body Diffuse A, it's then locked into Body Specular A, which locks it into Hand Specular A. But the head diffuse textures also have matching speculars, and there can only be one seed, so which diffuse should it be? One way or another the patcher is going to have to do some guessing. Enabling manual seed selection is possible, but it would be a fair bit of work both on the UI side (every time a seed is selected the UI would have to check that it's a top-level subgroup, and that no other top-level subgroups are selected) and on the patcher side (would have to run it through the gauntlet of "what happens if some subgroup(s) are set via Specific NPC Assignment / Consistency / ForceIf). 

A more robust solution would just be to edit the config file to make the required subgroup linkages bidirection. I could even add a "reciprocal" button for when a subgroup is dragged into the Required/Excluded list to make it faster. The current config files don't have reciprocal linkages because a) the patcher, as you mentioned, eventually figures out the correct correct combination with unidirectional linkages fairly quickly, and b) it takes some work to set up the bidirectional linkages without a reciprocal button, and I haven't had time to do it yet. But you're correct that it does clog up the verbose log a bit.

**Comment by HitBug83** [comment]
I understand, I was hoping it would be not so hard to set up.

SynthEBD is great as it stands, and thank you again for it. I'll just fill my configs with more links and allowances.

Without any pressure, just for the sake of brainstorming, please let me elaborate a bit.

On the user side, I don't think it would be this hard to make it work because it would follow the reasoning we do when we set the links and allowances up. The idea would be to follow a branched path starting by one of the main subgroups defined as the seed pool. It would definitively require a good knowledge of how the patching works (which I'm not sure to have), but it is already hard to set a flawless config from scratch without such knowledge.

Here is an example on how I could do a basic setup with this option :

1. I set all my diffuse heads and restrict them to whichever races/ages I want. I force the patcher to pick diffuse head only as a seed. (diffuse head in the first position in the tree)
2. I link the corresponding diffuse bodies and hands, with allowed attributes if I want when there is more than one option.
3. I link the corresponding specular to each diffuse texture.
4. I set the normal map heads mostly with race-specific allowance. (normal head in the second position in the tree)
5. I link the corresponding normal bodies and hands options with allowances according to the NPC class or faction.
6. I don't really care about subsurface, but I could if I wanted.
7. I set BodySlides allowances on the bodies normal maps.

This is just one way to do it (I can start with bodies or normals if I want, allow randomization on specular, use probability weights...). But with this process, I can have a coherent and easy to tweak distribution, matching all the allowances I set, without having to set reciprocal linkage.

On the user end, I think it would be easier to follow the path of distribution, avoid oversights and mistakes like those you pointed out, and find and correct them if some have been done. If correctly done, being careful with ForceIfs, I can't think of a case where a potentially wanted option would be ruled out. And if I'm not mistaken, it would be a lighter work for the patcher because many unwanted combinations would be ruled out from the start.

**Comment by Piranha91** [comment]
I can see the appeal of the top-to-bottom logic. The complexities with specific/forced assignments could probably be handled. One thing I'm not so sure about is the probability weighting, which is supposed to be global between config files. In the original zEBD implementation, the patcher would actually pre-calculate all possible subgroup combinations and their associated combined rule sets, and then draw entire combinations for NPCs. This made probability weighting really simple, because the combination's weighting was just the product of its subgroup weightings. However, once people started installing enough config files, the patcher actually ended up crashing from exceeding RAM capacity due to all the different possible combinations of subgroup variants. To get around this I made the algorithm that you see in the verbose log, which picks subgroups one-by-one and backtracks if it gets stuck in a hole. This is actually why the seed subgroups exist, instead of just starting from the first top-level position - it's a way to give every weighted subgroup a chance to get picked. To give a blunt example, if we have:

HeadD_A (weight = 1) --> requires BodyD_A (Weight = 100)
HeadD_B (weight = 5) --> requires BodyD_B (Weight =1)

A user would expect the HD_A/BD_A combination to be 20x more likely than the HD_B/BD_B. But if you restrict the seed to HeadD, then the latter combination would actually be 5x more likely than the former. So I'm a bit concerned about making the probabilities wonky if I start allowing seed selection. That being said, I suppose I could allow it but set the default to false... I'll think about it.

**Comment by HitBug83** [comment]
I see, indeed I was myself wondering how the probabilities are calculated, I asked you about it the other day.

Maybe the verbose logs could give some insight on the probabilities at each step, expressed in %, to help the user understand what's going on ?

Well, anyway it is working fine in the current state, don't spend your time on it if it is not worth the effort.

**Comment by HitBug83** [comment]
There is a way to choose the subgroup seed with the actual build. I realized that the patcher considers Force Ifs when it picks the seed.

Allowed attribute = all races in the desired subgroup, with a higher Force If weight than others, and voilà.

With all my configs enabled, the patching time has been reduced from 1 minute down to 40-45 seconds.

There is an issue though : when there are several Force Ifs with the same weight at the same level, the patcher doesn't randomize the seed choice, so all NPCs are getting the first forced asset by alphabetical order. This is probably not intended.

Should I open a new issue ? I've already made a mess in this one !

**Comment by Piranha91** [comment]
Good thought! And thanks for that report; I'll look into it. Let's keep in this issue since it's already reported here.

**Comment by Piranha91** [comment]
I believe this last issue should be fixed in 0.7.8. Let me know if it still does not behave as expected. BTW I added an acknowledgement to you in the readme :) I really appreciate the level of detail with which you looked at the output - this project really benefits from rigorous QA testing as you are providing, as I simply don't have the bandwidth to catch everything. Much appreciated!

**Comment by HitBug83** [comment]
Thank you for the acknowledgement, I appreciate it !

Seed randomization = fixed
Consistency issue = fixed

As far as I can tell, everything looks good in the logs now. Thank you for your responsiveness !
