### ISSUE TITLE
Plus (+) button missing from UI for Morph Group Maps under Bodygen integration

### ISSUE THREAD

**Issue by daddydave-jpg** [Synthesis-Collective/SynthEBD#37]
Title says it all, already spoke with you in Discord. If you need refreshing on the issue, discord name is iSniperpls and I posted in the spawn-support 5-6 August. Thanks for all your hardwork!

**Comment by daddydave-jpg** [comment]
Also worth noting, I figured out how to manually add the combination requirements to the config, but it won't take the drop down menu selection.  Example code:
`  "RacialTemplateGroupMap": [
    {
      "Label": "top",
      "Races": [],
      "RaceGroupings": [],
      "Combinations": [
        {
          "Members": [
            "Bottom"
          ],
          "ProbabilityWeighting": 1.0
        }
      ]
    },
],`
Now in SynthEBD Morph Group Map has morph combinations with drop downs to select groups from. Unfortunately, I've found two issues. If I leave the json open in Notepad++ I can watch sEBD change my drop down choice when exiting the program. Example I have above says "Members": "Bottom", but I had actually selected "Tops" from the drop down. 

Second issue is when you have multiple groupings under Morph Group Map and you set a group in the drop down when you click away to another grouping and click back it zeroes out your drop down selection. Something similar happens with choosing race grouping in the same menu as well, though it's not instant like the groups drop down.

**Comment by Piranha91** [comment]
The missing button should now be fixed in 0.7.8.3. Regarding the issues in your second post, I had trouble replicating them. I think it might be due to the external json manipulations? The members of the dropdown list are populated from the other menus - did you add `Tops` to your `TemplateGroups` section as follows?

```
"TemplateGroups": [
    "Tops"
  ],
```

If it wasn't there, then whatever you wrote externally in the .json file will be "orphaned" and deleted when the patcher next saves. I'd recommend doing everything through the UI due to the complexity. 

If you still think this is a real issue with the new update, could you please take a video using ShareX or similar so I can see what's going on?

**Comment by daddydave-jpg** [comment]
Yes, the issue persists even using the UI. I did verify I have TemplateGroups in the json, which was placed there by the actual program and not by myself. The new version picks up the first Group from the list and autofills it into the Morph Group map, but adding more from there causes them to blank after clicking away. I'll get a video later. 

I also noticed that the BodyGenData folder that SynthEBD creates after patching is incorrect, it's simply missing the ".esp" in the folder name. Without that, the morph data will not be picked up in game.

**Comment by Piranha91** [comment]
Ah, thanks for that note about the .esp - the way SynthEBD stores the patch name changed a few updates ago and I didn't think to update BodyGen accordingly. Appreciate the report.

Regarding the other issue, if you could get at least a before/after picture to help point me at the issue, I'd appreciate it!

**Comment by Piranha91** [comment]
Actually, nevermind - I wrote too soon. I poked around and was able to replicate the issue you described. Will look into it. Thanks!

**Comment by Piranha91** [comment]
Ok, should be fixed in 0.7.8.5. Let me know if you still have the issue on the new build.
