### ISSUE TITLE
I created config files but they don't work properly.

### ISSUE THREAD

**Issue by Daikichi-Takahey** [Synthesis-Collective/SynthEBD#59]
I install from the archive and it works until the assets are downloaded, but after that it's not working.
After checking my config in Asset Config Files , I close SynthEBD and start SynthEBD again and it is unchecked.
And no texture distribution is allowed. Can you check the config if possible?
[SynthEBD.-REALORE ULTIMA CBBE 4K.zip](https://github.com/Synthesis-Collective/SynthEBD/files/9631435/SynthEBD.-REALORE.ULTIMA.CBBE.4K.zip)

**Comment by Piranha91** [comment]
It looks like even my existing config installers no longer work, which is odd because I haven't touched any of that code recently. I'll dig into it over the weekend; thanks for the heads up.

**Comment by Piranha91** [comment]
I was able to fix it on my end. Out of curiosity, are you using a pre-release version cloned from one of my commits? The code that broke config file installation was only changed after the most recent release.

**Comment by Daikichi-Takahey** [comment]
Created based on ''Tempered skin for F'' you created.
It was early in its release. I just learned today that the file was recently updated.

**Comment by Daikichi-Takahey** [comment]
Also, totally unrelated, but I've created a BIJIN,PAN,KS group so you can include it in the release if anyone wishes.
![スクリーンショット (55)](https://user-images.githubusercontent.com/100354903/192092866-e4026d1d-f9bf-4bad-8c95-1324efad18e6.png)
[BIJIN,PAN,KS group.zip](https://github.com/Synthesis-Collective/SynthEBD/files/9638471/BIJIN.PAN.KS.group.zip)

**Comment by Piranha91** [comment]
This should be fixed in 0.8.3. I think you maybe have done a bit of extra work :) - the new Mod attribute type can give you your BIJIN/PAN/KS group in just a couple clicks. Sorry, didn't realize you were putting that list together or I would have warned you there'd be an easier way.

**Comment by Daikichi-Takahey** [comment]
I tested my config today and unfortunately it didn't work.

**Comment by Daikichi-Takahey** [comment]
I wonder if this is the cause.
SynthEBD's asset distribution functionality depends on a month-to-month license of Eval-Expression.NET, and it appears this license has expired for the current build of SynthEBD. Please contact Piranha91 or another member of the Synthesis Collective to refresh this license by updating the Eval-Expression NuGet package. In the meantime, BodyGen, BodySlide, and Height distribution remain fully functional.

**Comment by Piranha91** [comment]
Yeah that would be it. I’ll update the nuget in a few hours, traveling now.

**Comment by Daikichi-Takahey** [comment]
It appears as soon as it is activated.
I was so focused on watching MLB that I didn't read the display😱

**Comment by Piranha91** [comment]
Hahaha no worries. I just released 0.8.3.1 with Eval bumped so it should let you run now.

**Comment by Daikichi-Takahey** [comment]
The message still appears. If there is an existing config, the message will appear at startup, if the config is deleted and then started, the message will appear the next time the config is installed.

**Comment by Daikichi-Takahey** [comment]
This seems to happen only with configs I have created and configs I have modified.

https://user-images.githubusercontent.com/100354903/193401498-a348c821-97fa-4536-a70e-4d5a667b9b8a.mp4

**Comment by Daikichi-Takahey** [comment]
Everything has gone wrong.
I will delete all settings and recreate the config from scratch.
