### ISSUE TITLE
Distribution Order is not saved when restarting SynthEBD

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#91]
Well, just as the title says, that new Distribution Order is not saved when restarting SynthEBD :)

**Comment by Piranha91** [comment]
Fixed in 0.9.2. Thanks!

**Comment by leonardovcr** [comment]
Thanks for the update Piranha, however it's still not saving for me :(

The order seems to change everytime I restart now :) Running SynthEBD with two mix-in assets here.

**Comment by Piranha91** [comment]
Please tell me it's working for you in 0.9.3 :D

**Comment by leonardovcr** [comment]
Thanks, fixed :)
